In [79]:
import numpy as np


## Data types and attributes

In [80]:
# numpy main data type is ndarray
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [81]:
type(a1)

numpy.ndarray

In [82]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,3,5]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 3, 5]]])

In [10]:
a1.ndim, a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [13]:
a1.size,a2.size,a3.size

(4, 9, 12)

In [18]:
# creating a DataFrame from a Numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Array

In [83]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [97]:
ones=np.ones((3,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [94]:
ones.dtype

dtype('float64')

In [95]:
type(ones)

numpy.ndarray

In [96]:
zeroes=np.zeros((3,3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [99]:
range_array=np.arange(3,100,5)
print(range_array)

range_arr=np.arange(2,100,2)
print(range_arr)

[ 3  8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [101]:
random_array=np.random.randint(0,100,size=(3,3))
random_arr=np.random.randint(0,100,size=(5,5))

In [103]:
print(random_array)

print(random_arr)

[[ 5 34 61]
 [19 46 60]
 [88 16 18]]
[[68 57 81 48 87]
 [57 55 23  7 87]
 [86 76 55 38 68]
 [50 14 78  3 40]
 [75 93 74 12 30]]


In [105]:
random_array.shape
print(random_arr.shape)

(5, 5)


In [107]:
np.random.random((3,3))

array([[0.09306271, 0.26058174, 0.82722938],
       [0.8629346 , 0.79051219, 0.08820393],
       [0.15984668, 0.90284207, 0.1411353 ]])

In [114]:
# pseudo random number
# np.random.seed()
np.random.seed()
random_arrayrand=np.random.randint(10,size=(5,3))
random_arrayrand

array([[0, 4, 9],
       [8, 3, 3],
       [6, 9, 4],
       [8, 8, 6],
       [7, 6, 9]])

## Different ways of viewing array and matrices

In [115]:
np.unique(random_arrayrand)

array([0, 3, 4, 6, 7, 8, 9])

In [116]:
a1[0:4]

array([1, 2, 3, 4])

In [123]:
print(a2)
a2[:3,:1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [4],
       [7]])

In [124]:
print(a3)
a3[:2,:3,:2]

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 3 5]]]


array([[[1, 2],
        [4, 5]],

       [[7, 8],
        [0, 3]]])

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
rand5=np.random.randint(10, size=(2,3,4,5))

In [67]:
rand5

array([[[[6, 9, 8, 9, 9],
         [4, 4, 1, 6, 8],
         [2, 5, 9, 8, 0],
         [7, 9, 7, 3, 3]],

        [[9, 3, 0, 7, 7],
         [0, 7, 4, 8, 4],
         [5, 8, 2, 0, 7],
         [9, 7, 3, 4, 8]],

        [[7, 6, 3, 6, 6],
         [3, 6, 7, 9, 2],
         [9, 2, 8, 9, 7],
         [9, 1, 9, 5, 9]]],


       [[[2, 1, 3, 5, 9],
         [2, 0, 0, 6, 3],
         [4, 2, 0, 1, 8],
         [1, 9, 4, 9, 8]],

        [[6, 9, 7, 9, 4],
         [6, 3, 6, 6, 9],
         [7, 1, 8, 3, 7],
         [9, 9, 5, 7, 0]],

        [[2, 3, 9, 9, 0],
         [1, 9, 2, 2, 6],
         [6, 2, 6, 6, 2],
         [7, 8, 4, 7, 7]]]])

In [70]:
rand5[:,:,:,:1]

array([[[[6],
         [4],
         [2],
         [7]],

        [[9],
         [0],
         [5],
         [9]],

        [[7],
         [3],
         [9],
         [9]]],


       [[[2],
         [2],
         [4],
         [1]],

        [[6],
         [6],
         [7],
         [9]],

        [[2],
         [1],
         [6],
         [7]]]])

## Manipulating and Comparing arrays 

### Arithmetic

In [125]:
a1

array([1, 2, 3, 4])

In [126]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [130]:
ones=np.ones(4)

In [131]:
ones

array([1., 1., 1., 1.])

In [132]:
a1+ones

array([2., 3., 4., 5.])

In [133]:
a1-ones

array([0., 1., 2., 3.])

In [135]:
a1*a1*a1*2

array([  2,  16,  54, 128])

In [136]:
a1/ones

array([1., 2., 3., 4.])

In [137]:
a1//ones

array([1., 2., 3., 4.])

In [139]:
a2**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [140]:
a2%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [141]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [142]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### Aggregation

In [143]:
# performing  the same operation on  a number of things.


In [144]:
listy=[1,2,3,4,5]

In [146]:
sum(a1)

10

In [147]:
np.sum(a1)

10

In [148]:
massivearray=np.random.random(100000)
massivearray[:100]

array([0.59407353, 0.83264459, 0.03754469, 0.09294609, 0.01032799,
       0.59802589, 0.55837023, 0.1819741 , 0.40756141, 0.33436406,
       0.42478561, 0.91662271, 0.12242826, 0.21532801, 0.41514306,
       0.77332669, 0.30927276, 0.77921194, 0.59565488, 0.70021169,
       0.64895943, 0.68420487, 0.20697133, 0.77584731, 0.14999553,
       0.03527462, 0.32195259, 0.38843083, 0.05871709, 0.0854779 ,
       0.36048623, 0.43226755, 0.1666618 , 0.92770152, 0.88680444,
       0.02692251, 0.45213957, 0.03857379, 0.97277651, 0.67594816,
       0.32526152, 0.47153101, 0.66740501, 0.56838809, 0.69379392,
       0.01942592, 0.22526432, 0.12205387, 0.16019037, 0.72558681,
       0.00863888, 0.57075853, 0.67766252, 0.00221845, 0.37542227,
       0.11590946, 0.65367425, 0.24083134, 0.6386206 , 0.45250946,
       0.14313971, 0.3764233 , 0.94841518, 0.70933018, 0.79346916,
       0.68839923, 0.61355965, 0.0792703 , 0.36070256, 0.7088205 ,
       0.35427399, 0.59587034, 0.22396632, 0.83075036, 0.61008

In [149]:
%timeit sum(massivearray) # sum from python function
%timeit np.sum(massivearray) # sum from numpy function

19.2 ms ± 929 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
56.7 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [150]:
# Standard deviation is a measure of spread out a group of numbers is from the mean
np.std(a2)

2.581988897471611

In [152]:
# variance = measure of average degree to which each number is different
# higher variance= wider range of numbers
# lower variance= lower range of numbers
np.var(a2)

6.666666666666667

In [153]:
np.sqrt(np.var(a2))

2.581988897471611

In [154]:
# Demo of std and var 
high_var=np.array([1,100,200,300,4000,5000])
low_var=np.array([2,4,6,8,10])

In [155]:
np.var(high_var),np.var(low_var)

(4296133.472222221, 8.0)

In [156]:
np.std(high_var),np.std(low_var)

(2072.711623024829, 2.8284271247461903)

In [157]:
np.mean(high_var),np.mean(low_var)

(1600.1666666666667, 6.0)

## Change the shape of input

### Reshaping and transposing

In [158]:
a2.shape


(3, 3)

In [159]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 3, 5]]])

In [161]:
a3.shape


(2, 2, 3)

In [171]:
a2=a2.reshape(3,1,3)

In [172]:
a2

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [176]:
# transpose
a2.T

array([[[1, 4, 7]],

       [[2, 5, 8]],

       [[3, 6, 9]]])

In [178]:
a2=a2*a2.T

In [179]:
a2

array([[[   1,   64,  441]],

       [[  64,  625, 2304]],

       [[ 441, 2304, 6561]]])

In [180]:
a1

array([1, 2, 3, 4])

In [183]:
a1=a1.reshape(2,2)

In [184]:
a1

array([[1, 2],
       [3, 4]])

In [185]:
a1.T

array([[1, 3],
       [2, 4]])

## Dot Product

In [186]:
v1=np.array([2,3,4])
v2=np.array([1,2,3])
v3=v1*v2

In [187]:
v3

array([ 2,  6, 12])

In [198]:
# Dot product
np.random.seed(0)
mat1=np.random.randint(10,size=(3,5))
mat2=np.random.randint(10,size=(5,3))
mat3=np.random.randint(10,size=(3,5))

In [199]:
mat1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [205]:
print(mat1)
print(mat3)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]
[[2 3 8 1 3]
 [3 3 7 0 1]
 [9 9 0 4 7]]


In [201]:
mat1*mat3 # Element wise product or hadamard product

array([[10,  0, 24,  3, 21],
       [27,  9, 35,  0,  4],
       [63, 54,  0, 32,  7]])

In [207]:
# now dot product
np.dot(mat1,mat2)

array([[ 90, 103,  62],
       [143, 132, 123],
       [197, 148, 151]])

In [210]:
stock=np.random.randint(10,size=(6,3))

In [211]:
stock

array([[3, 2, 7],
       [2, 0, 0],
       [4, 5, 5],
       [6, 8, 4],
       [1, 4, 9],
       [8, 1, 1]])

In [221]:
price=np.array([20,30,15])
price=price.reshape(3,1)

In [222]:
price


array([[20],
       [30],
       [15]])

In [224]:
sale=np.dot(stock,price)
sale


array([[225],
       [ 40],
       [305],
       [420],
       [275],
       [205]])

## Comparing Operator 

In [225]:
a1


array([[1, 2],
       [3, 4]])

In [226]:
a2

array([[[   1,   64,  441]],

       [[  64,  625, 2304]],

       [[ 441, 2304, 6561]]])

In [232]:
a2<=a2

array([[[ True,  True,  True]],

       [[ True,  True,  True]],

       [[ True,  True,  True]]])

In [233]:
a1>a1

array([[False, False],
       [False, False]])

## Sorting Array

In [238]:
random_arr

array([[68, 57, 81, 48, 87],
       [57, 55, 23,  7, 87],
       [86, 76, 55, 38, 68],
       [50, 14, 78,  3, 40],
       [75, 93, 74, 12, 30]])

In [239]:
np.sort(random_arr)

array([[48, 57, 68, 81, 87],
       [ 7, 23, 55, 57, 87],
       [38, 55, 68, 76, 86],
       [ 3, 14, 40, 50, 78],
       [12, 30, 74, 75, 93]])

In [240]:
np.argsort(random_arr)

array([[3, 1, 0, 2, 4],
       [3, 2, 1, 0, 4],
       [3, 2, 4, 1, 0],
       [3, 1, 4, 0, 2],
       [3, 4, 2, 0, 1]], dtype=int64)

In [241]:
a1

array([[1, 2],
       [3, 4]])

In [242]:
np.argsort(a1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [243]:
np.argmin(a1)

0

In [244]:
np.argmax(a1)

3

In [245]:
np.argmax(random_arr)

21

## Turn Images into Numpy Array

<img src="images/numpy-panda.png"/>

In [259]:
# turn an image into a numpy array
from matplotlib.image import imread
panda=imread("images/numpy-panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [261]:
panda.size, panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

In [262]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.